version: "2"
services:
  mysql:
    image: docker.dev.pardot.com/base/percona-server:5.5
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
  app:
    build: .
    environment:
      PORT: "4000"
      BIND: "0.0.0.0"
      CANOE_DATABASE_HOST: "mysql"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - mysql
