version: "2"
services:
  app:
    build: .
    environment:
      PULL_HOSTNAME: "local-1"
    links:
      - canoe
  canoe:
    build: ../canoe
    environment:
      PORT: "4000"
      BIND: "0.0.0.0"
      CANOE_DATABASE_HOST: "mysql"
    volumes:
      - ../canoe:/app
    ports:
      - "4000:4000"
    links:
      - mysql
  mysql:
    image: docker.dev.pardot.com/base/percona-server:5.5
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
