default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("BOXEN_MYSQL_USER", "root") %>
  password:

development:
  <<: *default
  database: explorer_development

test:
  <<: *default
  database: explorer_test
