---
globals:
  global:
    local:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
        role: master
        database: pardot_global
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        password:
      2:
        host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
        role: master
        database: pardot_global
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        password:
shards:
  1:
    local:
      1:
        host: mysql
        role: master
        database: pardot_shard1
        username: root
        password:
      2:
        host: mysql
        role: master
        database: pardot_shard1
        username: root
        password:
  2:
    local:
      1:
        host: mysql
        role: master
        database: pardot_shard2
        username: root
        password:
      2:
        host: mysql
        role: master
        database: pardot_shard2
        username: root
        password:
...
